name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint assets
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Lint GitHub Action assets
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          echo "::add-matcher::.github/actionlint-matcher.json"
          ./actionlint -color ./assets